insert into customer values (1, 'null', '23847', '234', null, 'joao@joao', 'Joao', 'oas', '98908');
insert into customer values (2, 'null','23847', '234', null, 'maria@maria', 'Maria', 'oas', '98908');
insert into customer values (3, 'null', '23847', '234', null, 'Marco@marco', 'Marco', 'oas', '98908');
insert into delivery_address_customer values (1, '234', 'ap', 'rua das flores', 'sp', 'sp', 3);
insert into delivery_address_customer values (2, '234', 'ap', 'rua dos cravos', 'mg', 'mg', 3);
insert into delivery_address_customer values (3, '234', 'ap', 'rua nova', 'bh', 'mg', 1);
insert into delivery_address_customer values (4, '234', 'casa', 'rua velha', 'manaus', 'am', 1);
insert into card_customer values (1, '2348', '324', null, 'Joao', 'credit', 1);
insert into card_customer values (2, '52', '324', null, 'Joao', 'mastercard', 1);
insert into card_customer values (3, '2348', '324', null, 'Maria', 'credit', 2);
insert into card_customer values (4, '2348', '324', null, 'Marco', 'credit', 1);
insert into product_type values (1,'medicamento');
insert into product_type values (2,'material medico');
insert into product values (1,'generico','cura dor','novalgina', 10, 1);
insert into product values (2,'boa','protese','ferro', 1000, 2);
insert into product values (3,'doril','cura dor','doril', 100, 1);
insert into product values (4,'boa','maca','cama', 1000, 2);
insert into product values (5,'aaa','aaa','aaa', 10, 2);
insert into status_order values (1, 'aguardando pagamento');
insert into status_order values (2, 'cancelado');
insert into status_order values (3, 'aprovado');
insert into purchase_order values(1, 'cartao', null, 0, 1, 1);
insert into purchase_order values(2, 'boleteo', null, 0, 1, 2);
insert into purchase_order values(3, 'cartao', null, 0, 1, 3);
insert into purchase_order values(4, 'cartao', null, 0, 2, 1);
insert into purchase_order values(5, 'boleteo', null, 0, 3, 1);
insert into purchase_order values(6, 'cartao', null, 0, 2, 2);
insert into product_order values (1, 2, 1, 1);
insert into product_order values (2, 3, 2, 2);
insert into product_order values (3, 3, 3, 3);
insert into product_order values (4, 3, 4, 4);
insert into product_order values (5, 3, 1, 5);
insert into product_order values (6, 3, 1, 6);
insert into provider values (1, 'LTDA emp', 232323, 'José', 'jose@jose', 3248, 'admin', 'rua dos cravos', 'bh', 'mg', 23423, 'emp');
insert into provider values (2, 'LTDA emp1', 232323, 'Josevildo', 'josevildo@emp', 3248, 'admin', 'rua dos cravos', 'bh', 'mg', 23423, 'emp');
insert into provider values (3, 'LTDA emp', 232323, 'Josevaldo', 'josevaldo@jose', 3248, 'admin', 'rua dos cravos', 'bh', 'mg', 23423, 'emp');
insert into provider_product values (1,1);
insert into provider_product values (1,2);
insert into provider_product values (2,3);
insert into provider_product values (1,4);
